### ISSUE TITLE
Error code in install-otp

### ISSUE THREAD

**Issue by LostKobrakai** [erlef/setup-elixir#4]
I'm trying out this action:

```yaml
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: '1.11.3'
          elixir-version: '23.2'
```

But I get this error when it's executed:
`Error: The process '/home/runner/work/_actions/erlef/setup-elixir/v1/dist/install-otp' failed with exit code 8`
